# drivers/mxc/Makefile
obj-$(CONFIG_MXC_IPU_V3)		+= ipu3/
obj-$(CONFIG_MXC_VPU)                   += vpu/
obj-$(CONFIG_MXC_AMD_GPU)              += amd-gpu/
obj-$(CONFIG_MXC_GPU_VIV)              += gpu-viv/
